package com.lego.namnv.core.common.jdbcpool.supplier;

import com.github.benmanes.caffeine.cache.AsyncCache;
import com.github.benmanes.caffeine.cache.Caffeine;
import com.lego.namnv.core.common.collection.LegoCollectionUtil;
import com.lego.namnv.core.common.jdbcpool.config.JdbcHostRequirement;
import com.lego.namnv.core.common.jdbcpool.config.JdbcHostSpec;
import com.lego.namnv.core.common.jdbcpool.exception.JdbcConnectionException;
import com.lego.namnv.core.common.jdbcpool.host.JdbcHost;
import com.lego.namnv.core.common.sql.SqlQueryMeta;
import com.lego.namnv.core.common.comp.AbstractLifeCycle;
import com.lego.namnv.core.common.jdbcpool.config.JdbcConfig;
import com.lego.namnv.core.common.jdbcpool.host.PgHostInfo;
import com.lego.namnv.core.common.jdbcpool.host.JdbcHostStatus;
import io.vertx.core.Vertx;
//import io.vertx.pgclient.PgConnection;
import io.vertx.sqlclient.SqlConnection;
import lombok.NonNull;
import lombok.extern.log4j.Log4j2;

import java.net.ConnectException;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.stream.Collectors;

import static com.lego.namnv.core.common.exception.ExceptionUtils.getRootCause;

@Log4j2
class SensingConnectionSupplier extends AbstractLifeCycle implements JdbcConnectionSupplier {

    private final @NonNull JdbcConfig config;
    private final @NonNull List<JdbcHost> hosts;
    private final @NonNull AsyncCache<JdbcHostSpec, PgHostInfo> hostInfoCache;
    private final Vertx vertx;

    SensingConnectionSupplier(JdbcConfig config, Vertx vertx) {
        this.vertx = vertx;
        this.config = config;
        this.hosts = initHosts();
        this.hostInfoCache = Caffeine.newBuilder() //
            .expireAfterWrite(config.getHostRecheckDuration()) //
            .buildAsync();
    }

    @Override
    public CompletionStage<SqlConnection> getConnection(SqlQueryMeta queryMeta) {
        if (this.hosts.size() == 1)
            return this.hosts.get(0).getConnection();

        var hosts = new ArrayList<>(this.hosts);
        if (config.isLoadBalanceHosts())
            Collections.shuffle(hosts);

        return continueFindSuitableHost(queryMeta, hosts.iterator());
    }

    @Override
    protected void doStop(CompletableFuture<Void> stopFuture) {
        CompletableFuture.allOf(LegoCollectionUtil.transformToArray(hosts, JdbcHost::stop, CompletableFuture[]::new))
            .whenComplete((v, e) -> {
                if (Objects.isNull(e)) {
                    stopFuture.complete(v);
                } else {
                    stopFuture.completeExceptionally(e);
                }
            });
    }

    private List<JdbcHost> initHosts() {
        if (config.getHostSpecs().isEmpty())
            throw new IllegalArgumentException("No host provided");

        return config.getHostSpecs().stream()
            .map(spec -> JdbcHost.builder()
                .vertx(vertx)
                .host(spec.getHost())
                .port(spec.getPort())
                .databaseType(config.getDatabaseType())
                .user(config.getUser())
                .password(config.getPassword())
                .database(config.getDatabase())
                .maxPoolSize(config.getMaxPoolSize())
                .maxWaitQueueSize(config.getMaxWaitQueueSize())
                 .autoGeneratedKeys(config.isAutoGeneratedKeys())
                .build())
            .collect(Collectors.toUnmodifiableList());
    }

    private CompletionStage<PgHostInfo> getHostInfo(JdbcHost host) {
        return hostInfoCache.get(host.getHostSpec(), (key, executor) -> host.getHostInfo(config.getHostRequirement()));
    }

    private boolean checkSuitable(SqlQueryMeta queryMeta, PgHostInfo hostInfo) {
        if (hostInfo.getStatus() == JdbcHostStatus.CONNECT_FAIL)
            return false;
        return config.getHostRequirement() == JdbcHostRequirement.ANY //
            || hostInfo.getStatus() == JdbcHostStatus.PRIMARY //
            || queryMeta.isReadonly();
    }

    private CompletionStage<SqlConnection> continueFindSuitableHost(SqlQueryMeta queryMeta, Iterator<JdbcHost> it) {
        if (!it.hasNext())
            return CompletableFuture.failedStage(new JdbcConnectionException("No connection available"));

        var host = it.next();
        return getHostInfo(host).thenCompose(hostInfo -> {
            if (!checkSuitable(queryMeta, hostInfo))
                return continueFindSuitableHost(queryMeta, it);

            return host.getConnection() //
                .exceptionally(ex -> {
                    var rootCause = getRootCause(ex);
                    if (rootCause instanceof ConnectException) {
                        hostInfo.reportConnectFail();
                    } else {
                        log.error("Error while taking connection from host: {}", hostInfo.getSpec(), ex);
                    }
                    return null;
                }) //
                .thenCompose(conn -> {
                    if (conn == null)
                        return continueFindSuitableHost(queryMeta, it);
                    log.debug("got connection from: {}", host.getHostSpec());
                    return CompletableFuture.completedStage(conn);
                });
        });
    }

}
