package com.lego.namnv.core.common.jdbcpool.config;

import com.lego.namnv.core.common.jdbcpool.host.DatabaseType;
import com.lego.namnv.core.common.jdbcpool.supplier.SupplierType;
import com.lego.namnv.core.common.support.ParsedUri;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.Singular;
import org.apache.commons.lang3.EnumUtils;
import org.apache.commons.lang3.math.NumberUtils;

import java.time.Duration;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static java.util.Objects.isNull;

@Getter
@Builder(access = AccessLevel.PRIVATE)
public class JdbcConfig {

    private static final int DEFAULT_MAX_POOL_SIZE = 8;
    private static final int DEFAULT_MAX_WAIT_QUEUE_SIZE = 128;
    private static final Set<String> CUSTOM_PROPERTIES = Set.of("useSSL", "pemRootCaPath", "pemRootCa", "trustAll",
            "loadBalanceHosts", "hostRecheckDurationSecond", "hostRequirement", "masterIndex");
    private static final Set<String> POOL_PROPERTIES = Set.of("maxSize", "maxWaitQueueSize", "idleTimeout",
            "idleTimeoutUnit", "poolCleanerPeriod", "connectionTimeout", "connectionTimeoutUnit");

    private DatabaseType databaseType;
    private String user;
    private String password;
    private String database;

    @Builder.Default
    private SupplierType supplierType = SupplierType.STEADY;
    @Singular
    private List<JdbcHostSpec> hostSpecs;
    @Singular
    private Map<String, String> customProperties;
    @Singular
    private Map<String, String> connectionProperties;
    @Singular
    private Map<String, String> poolProperties;

    private boolean autoGeneratedKeys = true;

    public static JdbcConfig from(String uriString) {
        var parsedUri = ParsedUri.parse(uriString);
        return from(parsedUri);
    }

    public static JdbcConfig from(ParsedUri parsedUri) {
        if (isNull(parsedUri.getDatabaseType())) {
            parsedUri = parsedUri.toBuilder().databaseType("postgres").build();
        }
        var builder = builder() //
                .database(parsedUri.getPath()) //
                .user(parsedUri.getUser()) //
                .password(parsedUri.getPassword()) //
                .databaseType(DatabaseType.valueOf(parsedUri.getDatabaseType().toUpperCase()))
                .supplierType( //
                        switch (parsedUri.getScheme().toLowerCase()) {
                            case "steady" -> SupplierType.STEADY;
                            case "sensing" -> SupplierType.SENSING;
                            default -> throw new IllegalArgumentException(
                                    "Unsupported scheme, use steady, sensing");
                        });
        var addresses = parsedUri.getParsedAddresses(5432);
        if (addresses != null)
            for (var address : addresses)
                builder.hostSpec(new JdbcHostSpec(address));

        var params = parsedUri.getParams();
        if (params != null)
            for (var item : params.entrySet()) {
                var key = item.getKey();
                var value = item.getValue();
                if (CUSTOM_PROPERTIES.contains(key)) {
                    builder.customProperty(key, value);
                } else if (POOL_PROPERTIES.contains(key)) {
                    builder.poolProperty(key, value);
                } else {
                    builder.connectionProperty(key, value);
                }
            }

        return builder.build();
    }

    public int getMasterIndex() {
        return NumberUtils.toInt(customProperties.get("masterIndex"), 0);
    }

    public int getMaxWaitQueueSize() {
        return NumberUtils.toInt(poolProperties.get("maxWaitQueueSize"), DEFAULT_MAX_WAIT_QUEUE_SIZE);
    }

    public int getMaxPoolSize() {
        return NumberUtils.toInt(poolProperties.get("maxPoolSize"), DEFAULT_MAX_POOL_SIZE);
    }

    public JdbcHostRequirement getHostRequirement() {
        return EnumUtils.getEnumIgnoreCase(JdbcHostRequirement.class,
                customProperties.getOrDefault("hostRequirement", "any"));
    }

    public boolean isLoadBalanceHosts() {
        return Boolean.parseBoolean(customProperties.getOrDefault("loadBalanceHosts", "true"));
    }

    public boolean isSsl() {
        return Boolean.parseBoolean(customProperties.getOrDefault("useSSL", "false"));
    }

    public boolean isTrustAll() {
        return Boolean.parseBoolean(customProperties.getOrDefault("trustAll", "true"));
    }

    public String getPemRootCaPath() {
        return customProperties.get("pemRootCaPath");
    }

    public String getPemRootCa() {
        return customProperties.get("pemRootCa");
    }

    public Duration getHostRecheckDuration() {
        var duration = customProperties.get("hostRecheckDurationSecond");
        if (isNull(duration) || duration.isBlank()) {
            return Duration.ofSeconds(10);
        }
        return Duration.ofSeconds(Integer.parseInt(duration));
    }

}
