imageId: nnv98/harbor:1.1.32
istio:
  sidecar_inject: true

global:
  environment: dev
  baseDomain: lego.dev
  hazelcast:
    configMap: hazelcast-files
  vertx:
    mainCluster:
      name: vertx-land-cluster
      label:
        key: lego/vertx-cluster
        value: vertx-land-cluster
