lua_package_path "/usr/local/lib/lua/?.lua;/opt/v2/?/?.lua;/opt/v2/common/?.lua;;";

server {
    listen 80 default;
    server_name _;
    default_type text/html;

    lua_code_cache on;
    include resolvers.conf;

    location /v2/api/upload {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,orgId,Pragma,Connection,Accept,Origin,Referer,Accept-Language,Accept-Encoding,responseType';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        if ($request_method = 'OPTIONS') { return 200; }
        content_by_lua_file /opt/v2/file/upload.lua;
    }


    location /v2/api/download {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,orgId,Pragma,Connection,Accept,Origin,Referer,Accept-Language,Accept-Encoding,responseType';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        if ($request_method = 'OPTIONS') {
            return 200;
        }
        content_by_lua_file /opt/v2/file/download.lua;
    }

    location /v2/api/thumbnail {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,orgId,Pragma,Connection,Accept,Origin,Referer,Accept-Language,Accept-Encoding,responseType';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        if ($request_method = 'OPTIONS') {
            return 200;
        }
        content_by_lua_file /opt/v2/file/get-thumbnail.lua;
    }

    location @sendfile {
        internal;
        root /home/luklak/v2;
        try_files $uri =404;
        header_filter_by_lua_block {
            ngx.header["Access-Control-Allow-Origin"] = "*"
            ngx.header["Access-Control-Allow-Methods"] = "GET,POST,OPTIONS"
            ngx.header["Access-Control-Allow-Headers"] = "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,orgId,Pragma,Connection,Accept,Origin,Referer,Accept-Language,Accept-Encoding,responseType"
            ngx.header["Access-Control-Expose-Headers"] = "Content-Length,Content-Range"
            ngx.header["Cache-Control"] = "no-cache"
            ngx.header["Content-Disposition"] = "attachment; filename=\"" .. ngx.header["X-File-Name"] .. "\""
        }
    }

     location @getthumbnail {
            internal;
            expires max;
            etag off;
            if_modified_since off;
            root /home/luklak/v2;
            try_files $uri =404;
            header_filter_by_lua_block {
                ngx.header["Access-Control-Allow-Origin"] = "*"
                ngx.header["Access-Control-Allow-Methods"] = "GET,POST,OPTIONS"
                ngx.header["Access-Control-Allow-Headers"] = "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,orgId,Pragma,Connection,Accept,Origin,Referer,Accept-Language,Accept-Encoding,responseType"
                ngx.header["Access-Control-Expose-Headers"] = "Content-Length,Content-Range"
                ngx.header["Content-Disposition"] = "filename=\"" .. ngx.header["X-File-Name"] .. "\""
            }
        }
}
