apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/monitor: "true"
spec:
  selector:
    app: {{.Chart.Name }}
  type: NodePort
  ports:
    - name: socket
      port: 9999
      targetPort: 9999
      nodePort: 31001
    - name: http
      port: 8085
      targetPort: 8085
      nodePort: 31002