---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kpanic.
--- DateTime: 10/4/21 5:35 PM
---
---
local cjson = require "cjson"
local http = require "resty.http"
local const = require "fsconst"
local server_id = const.server_id
local jad_file = const.jad_file
local jad_files = const.jad_files
local jad_update_done_uri = const.jad_update_done_uri
local jad_file_get = const.jad_file_get

local _M = {}

function _M.create_file_path(org_id, token, params)
    local conn = http.new()
    local res, err = conn:request_uri(jad_file, {
        pool = 'jad',
        pool_size = 16,
        backlog = 1024,
        method = 'POST',
        headers = {
        },
        query = params,
    })
    return handle_response(res, err)
end

function _M.upload_done(body, params)
    local conn = http.new()
    encoded_body = cjson.encode(body)
    local res, err = conn:request_uri(jad_update_done_uri, {
        pool = 'jad-vip',
        pool_size = 16,
        backlog = 1024,
        method = 'POST',
        query = params,
        body = encoded_body
    })
    return handle_response(res, err)
end

function _M.get_file_path(org_id, token, params)
    local conn = http.new()
    local res, err = conn:request_uri(jad_file_get, {
        pool = 'jad',
        pool_size = 16,
        backlog = 1024,
        method = 'GET',
        headers = {
            ['orgId'] = org_id,
            ['Authorization'] = token,
        },
        query = params,
    })
    return handle_response(res, err)
end

function _M.get_files(org_id, token, params)
    local conn = http.new()
    local res, err = conn:request_uri(jad_files, {
        pool = 'jad',
        pool_size = 16,
        backlog = 1024,
        method = 'GET',
        headers = {
            ['orgId'] = org_id,
            ['Authorization'] = token,
        },
        query = params,
    })
    return handle_response(res, err)
end

function handle_response(res, err)
    if err then
        ngx.log(ngx.ERR, "Error:", err)
        return res, err
    end

    if res.status ~= 200 then
        ngx.log(ngx.ERR, "Error: Status is not 200. Status:", res.status, " Body:", res.body)
        return nil, res.body
    end

    local data = cjson.decode(res.body)
    resp_err = data.error
    if resp_err then
        ngx.log(ngx.ERR, "Error:", resp_err)
        return nil, resp_err
    end

    return data, nil
end

return _M