apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-files
data:
  app.yaml: |
    basePackage: com.lego.namnv
    hazelcast:
      file: /hazelcast-files/hazelcast.xml
      props: { }
    admEventBus:
      address: ${HOSTNAME}
      tags: private
      printStackTrace: false
    publicHttp:
      tags: public
      port: 8085
      path:
      headers:
        content-type: application/json
      printStackTrace: false
    chatSocket:
      host: 0.0.0.0
      port: 9999
      path: /connect
      serviceName: eb_gossip_adm
    database:
      parsedUri:
        databaseType: postgres
        scheme: steady
        addresses:
          - postgres:5432
        path: pingo
        user: pingo
        password: pingo-local-dev
        params:
          maxSize: 8
          maxWaitQueueSize: 1024
  log4j2.xml: |
{{ .Files.Get "config/log4j2.xml" | indent 4 }}