package com.pingo.core.common.jdbcpool.host;


import com.pingo.core.common.comp.AbstractLifeCycle;
import com.pingo.core.common.exception.ExceptionUtils;
import com.pingo.core.common.jdbcpool.config.JdbcHostRequirement;
import com.pingo.core.common.jdbcpool.config.JdbcHostSpec;
import com.pingo.core.common.jdbcpool.host.url.JdbcUrlProvider;
import com.pingo.core.common.sql.SqlQuery;
import com.pingo.core.common.sql.SqlSingleResult;
import io.vertx.jdbcclient.JDBCConnectOptions;
import io.vertx.jdbcclient.JDBCPool;
import io.vertx.sqlclient.Pool;
import io.vertx.sqlclient.PoolOptions;
import io.vertx.sqlclient.SqlConnection;
import lombok.Getter;
import lombok.NonNull;
import lombok.extern.log4j.Log4j2;

import java.net.ConnectException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

import static com.pingo.core.common.jdbcpool.host.JdbcHostStatus.*;


@Log4j2
class JdbcHostImpl extends AbstractLifeCycle implements JdbcHost {

    @Getter
    private final @NonNull JdbcHostSpec hostSpec;
    private final @NonNull Pool pool;

    JdbcHostImpl(PgHostBuilder builder) {
        this.hostSpec = new JdbcHostSpec();
        if (builder.host() != null)
            hostSpec.setHost(builder.host());
        if (builder.port() != null)
            hostSpec.setPort(builder.port());
        this.pool = initPool(builder);
    }

    @Override
    public CompletableFuture<PgHostInfo> getHostInfo(JdbcHostRequirement hostRequirement) {
        return getConnection() //
            .thenCompose(connection -> {
                if (hostRequirement == JdbcHostRequirement.ANY)
                    return connection.close() //
                        .map(any -> CONNECT_OK) //
                        .toCompletionStage();
                return isPrimary(connection) //
                    .thenApply(primary -> primary ? PRIMARY : SECONDARY);
            }) //
            .exceptionally(ex -> {
                var rootCause = ExceptionUtils.getRootCause(ex);
                if (!(rootCause instanceof ConnectException))
                    log.error("error while  get host info for: {}", hostSpec, ex);
                return JdbcHostStatus.CONNECT_FAIL;
            }) //
            .thenApply(stt -> PgHostInfo.builder() //
                .updatedAt(System.nanoTime()) //
                .spec(hostSpec) //
                .status(stt) //
                .build()) //
            .toCompletableFuture();
    }

    @Override
    public CompletionStage<SqlConnection> getConnection() {
        return this.pool.getConnection()//
            .toCompletionStage() //
            .thenApply(conn -> (SqlConnection) conn);
    }

    @Override
    protected void doStop(CompletableFuture<Void> stopFuture) {
        this.pool.close().onComplete(v -> stopFuture.complete(null)).onFailure(stopFuture::completeExceptionally);
    }

    private Pool initPool(PgHostBuilder builder) {
        var jdbcUrlProvider = JdbcUrlProvider.getJdbcUrl(builder.databaseType());
        var jdbcUrl = jdbcUrlProvider.createJdbcUrl(builder);

        var connectOptions = new JDBCConnectOptions()
            .setJdbcUrl(jdbcUrl)
            .setDatabase(builder.database())
            .setUser(builder.user())
            .setPassword(builder.password())
            // vertx-jdbc-client mac dinh autoGeneratedKeys=true (io.vertx.jdbcclient.SqlOptions), khien
            // PreparedStatement duoc mo voi Statement.RETURN_GENERATED_KEYS -- ket hop voi cau
            // "INSERT ... RETURNING <cot>" tuong minh cua Postgres, pgjdbc dua ket qua RETURNING qua
            // duong "generated keys" (chi doc duoc qua Statement.getGeneratedKeys()/property
            // JDBCPool.GENERATED_KEYS_LIST) thay vi ResultSet binh thuong -- code doc rows qua
            // spliterator/iterator chuan (xem ConversationMembershipRegistry#addMembers) luon ra RONG
            // du INSERT that su thanh cong (da xac minh: row co that trong Postgres nhung addMembers()
            // tra ve newlyAdded rong, lam mat thong bao CONVERSATION_ADDED cho member moi). Toan bo repo
            // khong co cot auto-increment/serial nao (PK deu la UUID sinh o client), nen khong can co
            // che generated-keys cua JDBC o dau ca -- tat han (khong dung builder.autoGeneratedKeys()
            // nua) de moi INSERT...RETURNING doc dung qua ResultSet thong thuong.
            .setAutoGeneratedKeys(false);

        var poolOptions = new PoolOptions();
        if (builder.maxPoolSize() != null)
            poolOptions.setMaxSize(builder.maxPoolSize());
        if (builder.maxWaitQueueSize() != null)
            poolOptions.setMaxWaitQueueSize(builder.maxWaitQueueSize());

        return JDBCPool.pool(builder.vertx(), connectOptions, poolOptions);
    }

    private CompletionStage<Boolean> isPrimary(SqlConnection connection) {
        return SqlQuery.of("show transaction_read_only").execute(connection) //
            .thenCompose(SqlSingleResult::closeThenGetFirst) //
            .thenApply(row -> row == null ? "" : row.getString("transaction_read_only")) //
            .thenApply(txRO -> "off".equalsIgnoreCase(txRO));
    }

}
