package com.pingo.core.common.jdbcpool.host;

import io.vertx.core.Vertx;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.net.PemTrustOptions;
import io.vertx.core.net.TrustOptions;
import lombok.Getter;
import lombok.NonNull;
import lombok.experimental.Accessors;

import java.util.HashMap;
import java.util.Map;

import static java.util.Objects.isNull;

@Getter
@Accessors(fluent = true)
public class PgHostBuilder {
    private DatabaseType databaseType;
    private Vertx vertx;
    private String host;
    private Integer port;
    private String database;
    private String user;
    private String password;
    private Integer maxPoolSize;
    private Integer maxWaitQueueSize;
    private boolean autoGeneratedKeys = true;
    private boolean ssl = false;
    private TrustOptions trustOptions;
    private boolean trustAll = true;
    private Map<String, String> properties = new HashMap<>();

    public PgHostBuilder ssl(boolean useSsl) {
        this.ssl = useSsl;
        return this;
    }

    public PgHostBuilder trustAll(boolean trustAll) {
        this.trustAll = trustAll;
        return this;
    }

    public PgHostBuilder pemRootCa(@NonNull String pemRootCa) {
        this.trustOptions = new PemTrustOptions() //
                .addCertValue(Buffer.buffer(pemRootCa));
        return this;
    }

    public PgHostBuilder pemRootCaPath(@NonNull String path) {
        this.trustOptions = new PemTrustOptions() //
                .addCertPath(path);
        return this;
    }
    public PgHostBuilder autoGeneratedKeys(@NonNull boolean autoGeneratedKeys) {
        this.autoGeneratedKeys = autoGeneratedKeys;
        return this;
    }
    public PgHostBuilder vertx(Vertx vertx) {
        this.vertx = vertx;
        return this;
    }

    public PgHostBuilder host(String host) {
        this.host = host;
        return this;
    }

    public PgHostBuilder databaseType(DatabaseType databaseType) {
        this.databaseType = databaseType;
        return this;
    }

    public PgHostBuilder port(Integer port) {
        this.port = port;
        return this;
    }

    public PgHostBuilder database(String database) {
        this.database = database;
        return this;
    }

    public PgHostBuilder user(String user) {
        this.user = user;
        return this;
    }

    public PgHostBuilder password(String password) {
        this.password = password;
        return this;
    }

    public PgHostBuilder maxPoolSize(Integer maxPoolSize) {
        this.maxPoolSize = maxPoolSize;
        return this;
    }

    public PgHostBuilder maxWaitQueueSize(Integer maxWaitQueueSize) {
        this.maxWaitQueueSize = maxWaitQueueSize;
        return this;
    }

    public PgHostBuilder property(String key, String value) {
        if (isNull(key)) {
            throw new IllegalArgumentException("Property key required");
        }
        if (isNull(value)) {
            throw new IllegalArgumentException("Property value required");
        }
        this.properties.put(key, value);
        return this;
    }

    public PgHostBuilder properties(Map<String, String> properties) {
        this.properties = properties;
        return this;
    }

    public JdbcHost build() {
        return new JdbcHostImpl(this);
    }

}
